# Generated by Django 5.2.8 on 2025-11-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('commissioner', 'Commissioner'), ('commissionee', 'Commissionee')], max_length=21),
        ),
    ]
