# Generated by Django 5.2.8 on 2025-11-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='campus_institution',
            field=models.CharField(blank=True, choices=[('BatStateU - Pablo Borbon (Main I)', 'BatStateU - Pablo Borbon (Main I)'), ('BatStateU - Alangilan (Main II)', 'BatStateU - Alangilan (Main II)'), ('BatStateU - ARASOF Nasugbu', 'BatStateU - ARASOF Nasugbu'), ('BatStateU - Lipa', 'BatStateU - Lipa'), ('BatStateU - Malvar (JPLPC)', 'BatStateU - Malvar (JPLPC)'), ('BatStateU - Balayan', 'BatStateU - Balayan'), ('BatStateU - Lemery', 'BatStateU - Lemery'), ('BatStateU - Rosario', 'BatStateU - Rosario'), ('BatStateU - San Juan', 'BatStateU - San Juan'), ('BatStateU - Lobo', 'BatStateU - Lobo'), ('BatStateU - Mabini', 'BatStateU - Mabini'), ('BatStateU - Lima', 'BatStateU - Lima')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.CharField(blank=True, choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('5th Year', '5th Year'), ("Master's Degree", "Master's Degree"), ('Doctorate / PhD', 'Doctorate / PhD')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('Beginner (No paid experience)', 'Beginner (No paid experience)'), ('Academic Projects Only (Thesis/Capstone)', 'Academic Projects Only (Thesis/Capstone)'), ('Freelancing / Commissions', 'Freelancing / Commissions'), ('Internship / OJT Experience', 'Internship / OJT Experience'), ('Professional / Industry Work', 'Professional / Industry Work')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_classification',
            field=models.CharField(blank=True, choices=[('Regular Student (Full Load)', 'Regular Student (Full Load)'), ('Irregular Student (Flexible Schedule)', 'Irregular Student (Flexible Schedule)'), ('Working Student', 'Working Student'), ('Graduating / Thesis Year', 'Graduating / Thesis Year'), ('Alumni / Graduate', 'Alumni / Graduate')], max_length=100, null=True),
        ),
    ]
