# Generated by Django 5.2.8 on 2025-11-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Done', 'Done'), ('Expired', 'Expired')], default='Active', max_length=20),
        ),
    ]
