# Generated by Django 5.2.8 on 2025-12-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Ongoing', 'Ongoing'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], default='Active', max_length=20),
        ),
    ]
